name: Workflow B

on:
  workflow_call:
    inputs:
      input_message:
        required: true
        type: string

jobs:
  process-message:
    runs-on: windows-latest
    steps:
      - name: Process message on Windows
        run: |
          echo "Message: ${{ inputs.input_message }}"
